import nacl from 'tweetnacl';

// ─── Per-call salt generation ────────────────────────────────────────────────
// A random 32-byte salt is generated by the CALLER for each new call.
// It is sent inside the call_request payload and used by both sides to derive
// an independent AES-GCM key even if the underlying NaCl shared secret is
// ever compromised (per-call forward secrecy).
export function generateCallSalt(): Uint8Array {
  return nacl.randomBytes(32);
}

export function encodeSalt(salt: Uint8Array): string {
  return btoa(String.fromCharCode(...salt));
}

export function decodeSalt(b64: string): Uint8Array {
  return Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
}

// ─── WhatsApp-style HKDF key derivation ──────────────────────────────────────
// Step 1: HKDF-Extract  → PRK  = HMAC-SHA-256(salt, NaCl_shared_secret)
// Step 2: HKDF-Expand   → key  = HMAC-SHA-256(PRK, "AuraCall" || 0x01) [first 32 bytes]
//
// This mirrors WhatsApp's approach: the NaCl shared secret (from X3DH-equivalent
// nacl.box.before) plays the role of the Signal-Protocol-derived IKM, and the
// per-call salt ensures each call gets a fresh key even with the same key pair.
export async function deriveCallSessionKey(
  partnerPublicKey: Uint8Array,
  mySecretKey: Uint8Array,
  salt: Uint8Array
): Promise<Uint8Array> {
  // 1. Compute NaCl shared secret (Curve25519 DH)
  const sharedSecret = nacl.box.before(partnerPublicKey, mySecretKey);

  // 2. Import shared secret as HMAC-SHA-256 key for HKDF-Extract
  const hkdfKey = await crypto.subtle.importKey(
    'raw',
    new Uint8Array(sharedSecret),
    { name: 'HKDF' },
    false,
    ['deriveBits']
  );

  // 3. HKDF: Extract + Expand in one step via Web Crypto
  const info = new TextEncoder().encode('AuraCall-v1');
  const bits = await crypto.subtle.deriveBits(
    {
      name: 'HKDF',
      hash: 'SHA-256',
      // Wrap in new Uint8Array() to guarantee ArrayBuffer (not SharedArrayBuffer)
      // backing — required by the Web Crypto BufferSource type.
      salt: new Uint8Array(salt),
      info: new Uint8Array(info),
    },
    hkdfKey,
    256  // 32 bytes = AES-256-GCM key
  );

  return new Uint8Array(bits);
}

// ─── Emoji Verification Fingerprint ─────────────────────────────────────────
// Hash the session key → take first 4 bytes → map each byte to an emoji from
// a curated set of 64 distinct emojis (6-bit index per emoji).
// Both peers display the same 4 emojis; if they match the call is authenticated.
//
// This mirrors Telegram's 4-emoji verification scheme.
const EMOJI_SET = [
  '🐶','🐱','🐭','🐹','🐰','🦊','🐻','🐼',
  '🐨','🐯','🦁','🐮','🐷','🐸','🐵','🐔',
  '🐧','🐦','🦆','🦅','🦉','🦇','🐺','🐗',
  '🐴','🦄','🐝','🐛','🦋','🐌','🐞','🐜',
  '🦟','🦗','🕷️','🦂','🐢','🦎','🐍','🦖',
  '🐙','🦑','🦐','🦞','🦀','🐡','🐠','🐟',
  '🐬','🐳','🐋','🦈','🐊','🐅','🐆','��',
  '🦍','🦧','🐘','🦛','🦏','🐪','🐫','🦒',
];

export async function generateCallFingerprint(sessionKey: Uint8Array): Promise<string[]> {
  // Wrap to ensure ArrayBuffer backing (not SharedArrayBuffer) for Web Crypto
  const hash = await crypto.subtle.digest('SHA-256', new Uint8Array(sessionKey));
  const bytes = new Uint8Array(hash);
  // Use first 4 bytes, map to 64-emoji set (6 bits of each byte)
  return [0, 1, 2, 3].map((i) => {
    const idx = bytes[i] % EMOJI_SET.length;
    return EMOJI_SET[idx];
  });
}
