export const STICKER_PACK = [
  { id: 'aura-heart', emoji: '❤️', label: 'Heart' },
  { id: 'aura-sparkles', emoji: '✨', label: 'Sparkles' },
  { id: 'aura-kiss', emoji: '😘', label: 'Kiss' },
  { id: 'aura-hug', emoji: '🫂', label: 'Hug' },
  { id: 'aura-flame', emoji: '🔥', label: 'Flame' },
  { id: 'aura-star', emoji: '⭐️', label: 'Star' },
  { id: 'aura-rose', emoji: '🌹', label: 'Rose' },
  { id: 'aura-moon', emoji: '🌙', label: 'Moon' },
  { id: 'aura-sun', emoji: '☀️', label: 'Sun' },
  { id: 'aura-cloud', emoji: '☁️', label: 'Cloud' },
  { id: 'aura-bubble', emoji: '🫧', label: 'Bubbles' },
  { id: 'aura-ring', emoji: '💍', label: 'Ring' },
  { id: 'aura-gift', emoji: '🎁', label: 'Gift' },
  { id: 'aura-love-letter', emoji: '💌', label: 'Letter' },
  { id: 'aura-eyes', emoji: '👀', label: 'Eyes' },
  { id: 'aura-bear', emoji: '🧸', label: 'Bear' },
  { id: 'aura-cat', emoji: '🐱', label: 'Cat' },
  { id: 'aura-dog', emoji: '🐶', label: 'Dog' },
  { id: 'aura-rabbit', emoji: '🐰', label: 'Rabbit' },
  { id: 'aura-panda', emoji: '🐼', label: 'Panda' },
];
