/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#e4c285",
        "on-primary": "#412d00",
        "outline": "#998f81",
        "error-container": "#93000a",
        "surface-dim": "#13131b",
        "inverse-on-surface": "#302f39",
        "on-tertiary-container": "#414049",
        "on-primary-fixed": "#261900",
        "on-tertiary-fixed": "#1b1b23",
        "on-secondary-fixed": "#261900",
        "surface-tint": "#e4c285",
        "surface-bright": "#393842",
        "surface-container-highest": "#34343d",
        "tertiary-fixed": "#e4e1ed",
        "on-background": "#e4e1ed",
        "on-secondary": "#412d00",
        "background": "var(--bg-primary)",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#e4c285",
        "on-tertiary": "#303038",
        "surface-container-high": "#292932",
        "inverse-surface": "#e4e1ed",
        "secondary-container": "#5a4312",
        "on-surface-variant": "#d0c5b5",
        "outline-variant": "#4d463a",
        "on-primary-fixed-variant": "#5a4312",
        "on-tertiary-fixed-variant": "#46464f",
        "on-error": "#690005",
        "on-surface": "#e4e1ed",
        "on-primary-container": "#543d0c",
        "primary-container": "var(--gold)",
        "tertiary-container": "#aeacb7",
        "surface-container-low": "#1b1b23",
        "secondary": "#e4c285",
        "primary": "var(--gold)",
        "surface-container-lowest": "#0d0d15",
        "inverse-primary": "#745a27",
        "tertiary-fixed-dim": "#c7c5d1",
        "on-secondary-container": "#d1b175",
        "surface-container": "var(--bg-secondary)",
        "on-secondary-fixed-variant": "#5a4312",
        "surface": "var(--bg-secondary)",
        "primary-fixed": "#ffdea4",
        "on-error-container": "#ffdad6",
        "tertiary": "#cac7d3",
        "secondary-fixed": "#ffdea5",
        "surface-variant": "#34343d",
        aura: {
          bg: {
            primary: 'var(--bg-primary)',
            secondary: 'var(--bg-secondary)',
            elevated: 'var(--bg-elevated)',
            surface: 'var(--bg-surface)',
          },
          gold: {
            DEFAULT: 'var(--gold)',
            light: 'var(--gold-light)',
            deep: 'var(--gold-deep)',
            muted: 'var(--gold-glow)',
          },
          rose: {
            DEFAULT: 'var(--rose)',
            light: 'var(--rose-light)',
            muted: 'var(--rose-muted)',
          },
          text: {
            primary: 'var(--text-primary)',
            secondary: 'var(--text-secondary)',
            muted: 'var(--text-muted)',
          },
          border: {
            subtle: 'var(--border-subtle)',
            medium: 'var(--border-medium)',
          },
          success: 'var(--success)',
          danger: 'var(--danger)',
        },
      },
      fontFamily: {
        headline: ["Noto Serif", 'Georgia', 'serif'],
        display: ['"Playfair Display"', 'Georgia', 'serif'],
        body: ["Plus Jakarta Sans", '"DM Sans"', 'system-ui', 'sans-serif'],
        label: ["Plus Jakarta Sans", 'system-ui', 'sans-serif']
      },
      fontSize: {
        'message': ['15px', { lineHeight: '1.6' }],
        'timestamp': ['11px', { lineHeight: '1.4' }],
      },
      borderRadius: {
        'bubble': '18px',
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      backgroundImage: {
        'sender-bubble': 'var(--sender-bubble)',
        'gold-shimmer': 'linear-gradient(135deg, var(--gold) 0%, var(--gold-light) 50%, var(--gold) 100%)',
      },
      boxShadow: {
        'glow-gold': '0 0 20px var(--gold-glow)',
        'glow-gold-strong': '0 0 30px var(--gold-glow)',
        'elevated': '0 8px 32px rgba(0, 0, 0, 0.3)',
        'bubble': '0 2px 8px rgba(0, 0, 0, 0.15)',
      },
      animation: {
        'pulse-gold': 'pulseGold 2s ease-in-out infinite',
        'bounce-in': 'bounceIn 0.3s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'fade-in': 'fadeIn 0.2s ease-out',
        'slide-up': 'slideUp 0.3s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'typing-dot': 'typingDot 1.4s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
      },
      keyframes: {
        pulseGold: {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(201, 169, 110, 0.4)' },
          '50%': { boxShadow: '0 0 0 8px rgba(201, 169, 110, 0)' },
        },
        bounceIn: {
          '0%': { opacity: '0', transform: 'scale(0.85)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        typingDot: {
          '0%, 60%, 100%': { transform: 'translateY(0)', opacity: '0.4' },
          '30%': { transform: 'translateY(-6px)', opacity: '1' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        glow: {
          '0%': { boxShadow: '0 0 5px rgba(201, 169, 110, 0.2)' },
          '100%': { boxShadow: '0 0 20px rgba(201, 169, 110, 0.4)' },
        },
      },
      backdropBlur: {
        'glass': '12px',
      },
    },
  },
  plugins: [],
}
